server:
  port: 8012
spring:
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: 192.168.43.246
      port: 8500
  # 定义zookeeper的连接信息
#    zookeeper:
#      connect-string: 192.168.43.246:2181
  application:
    name: cloud-order-consumer
#eureka:
#  client:
#    register-with-eureka: true
#    # 是否从EurekaServer抓取已经有的注册信息,默认为false,单节点无所谓,集群必须设置true/才能配合ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#  instance:
#    instance-id: order8002
#    prefer-ip-address: true