server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.246:8848
    sentinel:
      # sentinel的控制面板的ip和端口号
      transport:
        dashboard: localhost:8080
        # 默认8719端口,假如被占用会自动从8719开始依次的+1扫描
        port: 8719
# 暴露服务的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"