server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  #配置gateway的路由
  cloud:
    # 使用注册中心的服务名
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由的功能
      routes:
        - id: payment_route1
          # 改变配置的方式
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/result/**
            - After=2020-07-21T22:32:57.729+08:00[Asia/Shanghai]
eureka:
  client:
    register-with-eureka: true
    # 是否从EurekaServer抓取已经有的注册信息,默认为false,单节点无所谓,集群必须设置true/才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-gateway9527-service
    prefer-ip-address: true
    hostname: cloud-gateway9527-service


